# **Numpy Arrays**

In [31]:
#https://jalammar.github.io/visual-numpy/
#https://numpy.org/doc/stable/user/index.html
import numpy as np

In [3]:
my_list = [10,20,30,40]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list)

array([10, 20, 30, 40])

In [6]:
my_numpy_array = np.array(my_list)

In [7]:
type(my_numpy_array)

numpy.ndarray

In [8]:
my_numpy_array.max()

np.int64(40)

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.random(5)

array([0.59775261, 0.52505419, 0.43851679, 0.44606979, 0.9698337 ])

# **Array Arithmetic**

In [13]:
my_list1 = [1,2]
my_list2 = [3,4]

In [14]:
my_list1 + my_list2

[1, 2, 3, 4]

In [17]:
my_numpy_array1 = np.array(my_list1)
my_numpy_array2 = np.array(my_list2)

In [18]:
my_numpy_array1 + my_numpy_array2

array([4, 6])

In [19]:
my_numpy_array1 * my_numpy_array2

array([3, 8])

In [20]:
my_numpy_array1 - my_numpy_array2

array([-2, -2])

In [21]:
my_numpy_array1 / my_numpy_array2

array([0.33333333, 0.5       ])

In [22]:
my_numpy_array1 *5

array([ 5, 10])

In [23]:
my_list1 *5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [24]:
other_array = np.array([10,20,30,40,50])

In [25]:
other_array.max()

np.int64(50)

In [33]:
other_array.dot([1,2,3,4,5])

np.int64(550)

# **Arange and Indexing**

In [34]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
np_array = np.arange(0,10)

In [38]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np_array[1]

np.int64(1)

In [40]:
np_array[-1]

np.int64(9)

In [42]:
np_array[1:4:] #birinci indexte başlasın dördüncü indexte dursun

array([1, 2, 3])

In [43]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
np_array[2:6:2] #ikinci indexten başla altıncı indexte dur ikişer ilerle

array([2, 4])

In [46]:
np.random.randn(4)

array([ 0.03102526,  1.26591976, -1.19829568, -0.73469859])

In [47]:
np.random.randn(4,4)

array([[-1.29800371,  0.60831866, -0.77383473,  0.53023955],
       [ 1.65102405,  1.22479924,  1.37570468, -0.06288238],
       [ 0.81180764,  0.18754855, -0.05913744,  0.27673596],
       [-0.81083832, -0.31280232,  0.76210737, -0.47497835]])

In [48]:
np.random.randint(1,300,5)

array([264, 155, 232,  83, 142])

# **Matrices**

In [49]:
my_matrix = [[5,10],[15,20]]

In [50]:
my_matrix[0]

[5, 10]

In [51]:
my_matrix[1]

[15, 20]

In [52]:
my_matrix[0][1]

10

In [55]:
numpy_matrix = np.array([[5,10],[15,20]])
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [56]:
numpy_matrix[1][0]

np.int64(15)

In [57]:
numpy_matrix.sum()

np.int64(50)

In [58]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.random.random((3,2))

array([[0.80975641, 0.29745158],
       [0.80507275, 0.78284887],
       [0.93662192, 0.72492261]])

# **Matrix Arithmetic**

In [61]:
first_array = np.array([[10,20],[30,40]])
second_array = np.array([[5,15],[25,35]])

In [62]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [65]:
third_array = np.array([[50,60]])
third_array

array([[50, 60]])

In [66]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [67]:
fourth_array = np.array([[1,2,3,4,5]])

In [69]:
first_array + fourth_array # broadcast uyumsuzluğu

ValueError: operands could not be broadcast together with shapes (2,2) (1,5) 

In [70]:
third_array = np.array([[50],[60]])
third_array

array([[50],
       [60]])

In [71]:
first_array + third_array

array([[ 60,  70],
       [ 90, 100]])

# **Matrix Multiplication**

In [72]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [74]:
#dot product -> axb bxc

In [75]:
first_matrix = np.array([[10,20,30]])
first_matrix

array([[10, 20, 30]])

In [76]:
second_matrix = np.array([[2,3],[2,3],[2,3]])
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [77]:
first_matrix * second_matrix

ValueError: operands could not be broadcast together with shapes (1,3) (3,2) 

In [79]:
result = first_matrix.dot(second_matrix)

In [80]:
result

array([[120, 180]])

In [81]:
result.shape

(1, 2)

# **NumPy Operations**

In [82]:
new_array = np.random.randint(1,100,20)
new_array

array([ 7, 59, 84, 27, 24, 83,  2, 96, 84, 73, 78, 71, 21, 29, 40, 91, 57,
       52, 16, 71])

In [85]:
new_array > 25

array([False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True])

In [84]:
new_array[new_array > 25]

array([59, 84, 27, 83, 96, 84, 73, 78, 71, 29, 40, 91, 57, 52, 71])

In [86]:
#transpose & reshape

In [87]:
matrix_array = np.array([[10,20],[20,30],[30,40]])
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [88]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [89]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [90]:
random_arr = np.random.random((6,1))
random_arr

array([[0.99846152],
       [0.2285589 ],
       [0.75076926],
       [0.03542841],
       [0.88601192],
       [0.98591841]])

In [92]:
random_arr.shape

(6, 1)

In [93]:
random_arr.reshape(2,3)

array([[0.99846152, 0.2285589 , 0.75076926],
       [0.03542841, 0.88601192, 0.98591841]])

In [94]:
# z-score

In [95]:
data = np.array([10,12,13,15,18,25,100,105])

In [96]:
#outlier

In [97]:
mean = np.mean(data)
mean

np.float64(37.25)

In [98]:
data.sum() / len(data)

np.float64(37.25)

In [99]:
std = np.std(data)
std

np.float64(37.9333296719389)

In [100]:
z_score = (data-mean) / std
z_score

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [102]:
z_score[z_score > 1]

array([1.65421809, 1.78602829])

In [104]:
data[z_score > 1]

array([100, 105])

In [106]:
#math equations 
# 2x + 3y = 8 and 5x + 7y = 19

In [108]:
A = np.array([[2,3],[5,7]]) # coefficient 

In [109]:
b = np.array([8,19])

In [111]:
solution = np.linalg.solve(A,b)
solution

array([1., 2.])